sudo: false
language: scala
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - develop
scala:
  - 2.11.8
  - 2.12.1
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.sbt
    - $HOME/.ivy2
script:
  - ./bin/travis_build.sh
